name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: |
       cd Pharmacy 
       chmod +x gradlew
    - name: Build with Gradle
      run: |
       cd Pharmacy
        ./gradlew build
    - name: Android Emulator
    # You may pin to the exact commit or the version.
    # uses: vgaidarji/android-github-actions-emulator@30c50f42518922e01004c2152911bb458d33ff3b
    - uses: vgaidarji/android-github-actions-emulator@v1.0.1  
        
        
        
